apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # delete도 있음
  storageClassName: dev1
  nfs:
    path: /shared
    server: 211.183.3.99
